### ISSUE TITLE
Measurement parameters

### ISSUE THREAD

**Issue by pegahnikbakht** [virtee/sevctl#101]
I started a SEV-SNP VM (using https://github.com/AMDESE/AMDSEV), no I want to precalculate measurement value of attestation report, but I'm not sure in the command  `sevctl measurement build` which parameters should be provided for --tik and  --launch-measure-blob? What are these attributes?

**Comment by sza-1** [comment]
@pegahnikbakht you may create the integrity key (TIK) with `sevctl session`, before starting your VM, and may get measure blob from your hypervisor (e.g. QEMU) with `query-sev-launch-measure` command (via QMP interface).
