### ISSUE TITLE
Improve Microcode Support Identification

### ISSUE THREAD

**Issue by larrydewey** [virtee/sevctl#65]
I am thinking there is a better way for us to identify the models supported. We should discuss this more in-depth so we can iron out a less brittle approach.

**Comment by tylerfanelli** [comment]
@larrydewey To check for microcode support, we [identify if the current model is an EPYC processor](https://github.com/virtee/sevctl/blob/0b8a57cd78bcd306951acedb0463fd97636c3a14/src/ok.rs#L141). Is this what you are referring to?

**Comment by larrydewey** [comment]
Yes. It would probably be worthwhile to identify what model of microcode is supported.

**Comment by tylerfanelli** [comment]
Closed by #103
